[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.29"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]

[fuzz]
runs = 512

[invariant]
runs = 128
depth = 64

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
unichain_sepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"
lasna = "${LASNA_RPC_URL}"
